language: c
sudo: require
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
env:
  global:
    - OCAML_VERSION=4.04.2
    - DISTRO=debian-stable
    - PACKAGE=netlink
  matrix:
    - BASE_REMOTE=git://github.com/xapi-project/xs-opam
    - EXTRA_REMOTES=git://github.com/xapi-project/xs-opam
matrix:
  fast_finish: true
  allow_failures:
    - env: EXTRA_REMOTES=git://github.com/xapi-project/xs-opam
